### ISSUE TITLE
Can't update mbed-os version with 'mbed update' command

### ISSUE THREAD

**Issue by vince-zeng** [ARMmbed/mbed-os-example-nfc#54]
For example, I can't update the mbed-os version to mbed-os-5.15 which is used for OOB test.  To update to that version, I have to change the mbed-os.lib manully.

**Comment by 0xc0170** [comment]
You should use 5.15 branch - it contains the rc1 candidate sha already, see https://github.com/ARMmbed/mbed-os-example-nfc/tree/mbed-os-5.15

**Comment by vince-zeng** [comment]
Sorry, it seems that my test method is wrong. I will redo the test. Please close this issue. Thanks!
