### ISSUE TITLE
[5.10-OOB] Fail to fetch source code of eeprom driver

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-nfc#6]
eeprom_driver source code cannot be cloned because of an invalid URL in **eeprom_driver.lib**.
mbed-os-example-nfc/NFC_EEPROM/source/target/TARGET_M24SR/eeprom_driver.lib

https://github.com/ARMmbed/mbed-nfc-m24sr

**Comment by MarceloSalazar** [comment]
@soramame21 can you please confirm if this is now solved?
