### ISSUE TITLE
[5.10-OOB] mbed-os-example-nfc\NFC_EEPROM failed when building with IAR compiler

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-nfc#9]
mbed-os-example-nfc\NFC_EEPROM failed, when the example built with IAR compiler.
NFC tag can not be readd by an NFC reader APP on iphone.
the NFC tag can be read when the example code built with ARM compiler.

**Building command**
mbed compile -t IAR -m DISCO_L475VG_IOT01A -f -c
```Building an ndef message
failed to write (error: 16)
failed to read (error: 16)
Building an ndef message
failed to write (error: 16)
failed to read (error: 16)
Building an ndef message
failed to write (error: 16)
failed to read (error: 16)
```
**APP on iphone**
**NFC TagInfo** provided by NXP.

**Comment by ashok-rao** [comment]
@soramame21 : What happens on the phone? Does it read the tag? I had the same issue but my Android phone was able to read the tag (using the same app NFC TagInfo)..

**Comment by soramame21** [comment]
@ashok-rao Nothing can be found. no tag exists.

**Comment by paul-szczepanek-arm** [comment]
I verified this is the case but haven't got any fix yet.

**Comment by soramame21** [comment]
yes, the issue is not fixed by **mbed-os-5.10.0-rc2**

**Comment by pan-** [comment]
The issue is only visible with IAR with the ST EEPROM (it is not present when the PN512 is used). 
Note that the ST EEPROM library lives outside mbed-os so that shouldn't be a blocker on mbed-os repo.

**Comment by korjaa** [comment]
Reproduces with `mbed-os-5.14-rc2`.

**Comment by maciejbocianski** [comment]
fix is here https://github.com/ARMmbed/mbed-nfc-m24sr/pull/5

**Comment by jamesbeyond** [comment]
also seems this is know issue:
https://github.com/ARMmbed/mbed-os-example-nfc/tree/master/NFC_EEPROM#known-issues

**Comment by 0xc0170** [comment]
> fix is here ARMmbed/mbed-nfc-m24sr#5

This issue should be closed or not?

**Comment by ciarmcom** [comment]
@soramame21 thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@soramame21 it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by paul-szczepanek-arm** [comment]
IAR no longer supported
